### ISSUE TITLE
Make the presentation system reusable: add-on?

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-3-presentation#23]
## The issue

It'd be great if we could reuse the presentation system for multiple presentations:

- You can run game code in your slides
- The layout automatically adapts to your content so it's fast to create a new presentation
- We have access to Godot's powerful UI system, soon the new animation system to make it look and feel even better

## How can we do this?

I see two options:

- Make the presentation its own bare-bones project, and use something like git submodule to link it to different presentation projects. It's the way to manage dependency on other projects with git. 
- Make a Godot add-on so we can share it on the assets library. It would make it easier for people who don't have experience with git to use the system but I don't know how flexible the presentation would be in this case:
    - We would probably have to make at least two or three node types. E.g. `Presentation`, `PresentationSettings`, `SlideTemplate` so people can control many aspects of the presentation separately
    - This would allow people to create their own `SlideTemplate` from scratch, add their own animations etc. to create a brand new presentation look

I need some feedback from you, and I'd definitely need some help to do this. @henriiquecampos your feedback would be valuable as you're working with Godot's plugin system. Do you have an idea of the efforts it'd take to add a few node types?

**Comment by henriiquecampos** [comment]
Hey! It's a easy task to add new node types, as this by itself is just adding an inheritance entry to a parent `Node` adding a script to it as you can see in the **Platform Actor** [plugin.gd](https://github.com/pigdevstudio/platform_template/blob/master/source/addons/platform_actors/plugin.gd#L5-L8). But there are few limitations, which can be easily fixed. E.g. if you want to bring a full structure of a scene, let's say a `basic_slide.tscn` it will be needed to add some slightly lower level relation with the **Godot Editor**. For example:

```GDScript
func setup_character(character):
	var b = load(PATH + "state_machine.tscn").instance()
	var s = CollisionShape2D.new()
	character.name = "platform_actor_2d"
	character.add_child(s)
	character.add_child(b)
	s.set_owner(get_tree().get_edited_scene_root())
	b.set_owner(get_tree().get_edited_scene_root())
```
This method makes sure that some dependencies are added to the `root` (actually the first child of the root which would be the Scene root...guys gotta give a better name or at least a not ambiguous one to it :cry: ).

So let's say you want to add the following hierarchy:

- BasicSlide (which inherits a `Control` for example and carries a `GDScript`, this can be set easily through the `EditorPlugin`)
    - A `HBoxContainer`
    - A `Label`
    - A `Button`

All the `BasicSlide` children would have to be added manually, adding the current *edited scene* as their owner, this will make sure they are all exposed in the Scene Tree dock, thus they can be edited through inspector, and also will make sure they are part of the `.tscn` file when the *edited scene* is saved to disk.

This was my approach to the [Platform Actor Plugin](https://github.com/pigdevstudio/platform_template/blob/master/source/addons/platform_actors/plugin.gd) in order to add the dependencies so the users don't have to figure out by themselves what's possibly missing to make the *custom node* work.

ps: the above is meant to explain that adding a custom type/node is different than adding a scene, in the end the custom `Node` is the class it inherits + a script, nothing else. E.g. the **Platform Actor** is just a **KinematicBody2D** with a custom script, the actual scene structure has to be hard-coded.

**Comment by henriiquecampos** [comment]
Alright, something I noticed we can be used in our favor is instead of using only `Dictionary` to store `Slide` data, we could make use of `.tscn` as a container for it. Core advantages could be:

- It may solve #11 enabling any kind of transition actually
- More user friendly `Slide`design, e.g.: exposing `Slide.color` to the editor
- Each `Slide` is saved to disk allowing better re-usability 
- Allows a flexible approach to the *back-bone* design

This allows the usage of a very flexible, already known, structure that gives freedom to design each `Slide` taking advantage of the Godot Editor itself, allowing the seamless use of Godot's Animation System.

I see some obvious downsides with this approach but I think it pays off :thinking:

**Comment by NathanLovato** [comment]
> Maybe this become the standard approach to plugins, so isn't the case to design it with this in mind?

Thanks for the feedback! So I guess adding custom node types isn't worth it. We should use some Presentation node, SlideTemplate that all slides inherit from... and you need an entire hierarchy of nodes. People can just instance them from the add-on.

> Alright, something I noticed we can use in our favor is instead of using only Dictionary to store Slide data, we could make use of .tscn as a container for it. 

If you look at the commit history, that's how presentations worked initially. It seems simpler at first but it's a lot slower to create slides this way. You have to dive in the slide's tree, go change all the properties... There's no way to reorder with drag and drop... You can still load .tscn files instead of using text in the project for any given slide so that's supported.

**Comment by NathanLovato** [comment]
With Godot 3.1, we can register classes globally with `class_name`, and we might be able to register scenes as nodes in the editor: so let's not create an add-on for now. Just a reusable asset/base project would be nice, something you can add to your project as a git submodule or load from the asset library.
