### ISSUE TITLE
Review the existing slides to plan a solid 10 minutes pitch Godot

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-3-presentation#26]
I had to make a short presentation for an event in Osaka. As it turns out, for other events in Japan, they want 5 to 10-minute presentations as well.

I'd like a review of the itchy pixel presentation, should be loaded by default when you open the project right now. To start with, I need some brief notes and in an overview of how we could improve:

- **The structure**. This presentation is meant to give a sense of what Godot is, and to make people want to follow the project and try it. It has to amaze target users in a very short timeframe. it should answer questions like: what is Godot? why should I care? How do I get it? How do I learn to use it?
- The **media**: we need to show the most stunning and technically accomplished 2-D and 3-D projects in the engine
- I also want feedback on the **data structure**. Right now it's all in a GDScript dictionary, but I think it should be converted to JSON, so we can build tools to manage it. One of the main issues is supporting things like coloring the text for instance. but if the data is all JSON, we can create some text edit tools that you can toggle on and off when the presentation is playing. Hopefully, someone will be interested in contributing to that!

Keep it in note-taking style, I want a condensed review/organized bullet list(s) to get the discussion started and plan the work you'll do on the pres.

_I already plan to embed some gameplay demo from the Godot course/upcoming FOSS game project when it's ready, to really show the engine in action, show that the system is made in Godot and that it uses its advanced UI tools. Even in its current basic form, it impressed quite a few viewers already!_

**Comment by henriiquecampos** [comment]
Heyo, finally got my environment fixed to run Godot again.

So something that I realized is that we will need to know the audience first. This is mandatory because it can be the difference between removing some slides that aims for a more educational audience and or adding more slides aiming the educational audience. For instance, if it is a talk to game development studios they will most likely give more attention to its features, while if we are presenting to students, then they will care more about the games made with Godot and even content creators, so they have solid examples of what the engine can achieve and where they can find content, while if the presentation is for college teachers to adhere to the engine, then we shall focus on the structure, the languages it supports and depending on the type of college, even show the repository data, it is becoming common to ask students to solve issues from open source tools as exercises or homework.

The port to `.json` is something that will need some safe answer for the question: can Godot itself offers the tools for the management of the slide's content, or will we need an external tool for that? But since Godot has support to parse `.json` I think that nothing prevents from making simple plugins in Godot itself that handles. But I would stick to Godot's data strutures. For instance a tool that eases the use of RichTextLabel for coloring text.

That said...

## The structure

So I'd say a good structure would be:

1. What is Godot Engine
1. What can I achieve with it?
1. How easy is to achieve that?
1. What if I don't understand it?
1. Where can I acquire it?
1. I have a question!

The answer to each of these questions should not take more than 2min, so I think it is safe, the content is already on the current presentation so it won't take more work to create. It will depend more on "how it is answered" then on "what is answering it".

## Media

- [Current 3D demo](https://twitter.com/reduzio/status/1014314512135094272)
- [Headcase](https://youtu.be/ZR1Yfmr1KRM?t=11s) for more 3D
- [Protocorgi](https://youtu.be/ZR1Yfmr1KRM?t=21s) for 2D
- [Gun Toting Cats](https://youtu.be/ZR1Yfmr1KRM?t=1m51s) for more 2D

These are some that came out of my mind, but I'm sure there are lots with more eyecandy.

## Structure

Yeah, by going for `.json` we will be able to make tools seamlessly, both using plugins or tool scripts, and using outer tools, e.g. python. But I'd like to suggest to consider using Godot built-in data structure. Although you already moved from them to simple dictionaries, maybe we can think in a way to use them efficiently.

- Use json to standardize data structure
- Design a tool that abstract RichTextLabel features more intuitively
- Consider `tres` and `tscn` formats to design slides

**Comment by henriiquecampos** [comment]
> embed some gameplay demo from the Godot course/upcoming FOSS game project

You mean, playing the game's directly in the presentation? That would be awesome! 

But won't that be kinda of time consuming? 10min is a blink of an eye.

**Comment by NathanLovato** [comment]
> I'd like to suggest to consider using Godot built-in data structure.
> tscn formats to design slides

It's possible to make it work with tool scripts to enhance the editor, load and edit slides in the viewport... but it's probably quite a bit of work to make this efficient. As I told you before, at first the presentation worked with .tscn file, and it took ages to edit.

So imo it would take as much time to build the tools than to improve the pres, and then we'd likely face serious issues that'd require more tools: e.g. to translate the presentation in other languages. Hence JSON. It's not about making it work with external tools, but separating data from the slides' scenes.

**Comment by henriiquecampos** [comment]
Alright, so after reviewing slide by slide I think that this is a more concise feedback.

## Deponia PS4, Made with Godot

- Move to **Made with Godot**

## All-in-One Package

- Break into dedicated slides for each feature
- Add footage for each of said features
 
### New All in One Breakthrough Proposal

- Code (with available languages and their features)
  - Shaders
  - Bultin API
- Visual Editor (SceneTree and Node System, basically what currently is in **Great to Learn Game Code**)
  - 2D Editor 
    - [Tilemap](https://github.com/godotengine/godot/pull/20585)
    - UI (**Godot is a Godot Game** + **Complex User Interface**)
    - Animation (really emphasize this :stuck_out_tongue: )
  - 3D Editor
    - Use **Modern 3D Engine** (using some of the media mentioned in previously)

## Virtual Reality

- Use footage from [Bastiaan Olij Leap Motion?](https://www.youtube.com/watch?v=vumX-Or9J5U)

## Godot 3.0 is Out!

- Cut or mention 3.1 instead

## Godot is in Great Shape

- Mention the [popularization of the engine](https://itch.io/games/tag-godot-engine)
- Update data (?)
  - Maybe design a tool to scavenger the data and always keep it up to date? 

## Overall

- Allow window scaling
- Use update media with most recent
- Add a "Coming Soon" slide to showcase what is in the bake

**Comment by NathanLovato** [comment]
All good, let me prepare some issues for the two of us to tackle from that!
